module.exports = {
  Category: require("./category"),
  Assessment: require("./assessment"),
  Module: require("./module"),
  Question: require("./question"),
  Answer: require("./answer"),
  UserAnswer: require("./UserAnswer"),
  UserAssessment: require("./UserAssessment"),
  UserModule: require("./UserModule"),
  UserScore: require("./UserScore"),
  UserProfile: require("./UserProfile"),
  UserCart: require("./UserCart"),
  Feedback: require("./feedback.js"),
  Token: require("./token"),
  Chat: require("./chat"),
  Message: require("./message"),
  Contact: require("./contact"),
  CPQuestion: require("./cp.question"),
  CMQuestion: require("./cm.question"),
  CPUserAnswer: require("./cp.user.answer"),
  CMUserAnswer: require("./cm.user.answer"),
  CTQuestion: require("./ct.question"),
  CTUserAnswer: require("./ct.user.answer"),
};
