module.exports = {
  Category: require("./category"),
  Assessment: require("./assessment"),
  Module: require("./module"),
  Question: require("./question"),
  Answer: require("./answer"),
  UserAnswer: require("./UserAnswer"),
  UserAssessment: require("./UserAssessment"),
  UserModule: require("./UserModule"),
  UserScore: require("./UserScore"),
  UserProfile: require("./UserProfile"),
  UserCart: require("./UserCart"),
  NESTFeedback: require("./nest.feedback.js"),
  Token: require("./token"),
  Chat: require("./chat"),
  Message: require("./message"),
  Contact: require("./contact"),
  CMQuestion: require("./cm.question"),
  CMUserAnswer: require("./cm.user.answer"),
  DivergentResponse: require("./divergent.response"),
  DivergentScore: require("./divergent.score"),
  LeftRightStatement: require("./left.right.statements"),
  RatingStatement: require("./rating.statements"),
  UserResponse: require("./user.response"),
};
